### ISSUE TITLE
not an issue - fyi

### ISSUE THREAD

**Issue by johndpope** [saschaschramm/SwiftReinforce#6]
https://github.com/tanmayb123/OpenAI-Unsupervised-Sentiment-Neuron---Swift-for-TensorFlow

**Comment by johndpope** [comment]
https://github.com/tensorflow/swift-models/blob/stable/Gym/CartPole.swift

**Comment by saschaschramm** [comment]
Updated project.

**Comment by johndpope** [comment]
fyi 
https://github.com/eaplatanios/swift-retro
https://github.com/eaplatanios/swift-ale
https://github.com/eaplatanios/swift-rl
